apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-to-a-gka-cluster-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-app-to-a-gka-cluster
  template:
    metadata:
      labels:
        app: deploy-app-to-a-gka-cluster
    spec:
      containers:
      - name: deploy-app-to-a-gka-cluster
        image: europe-west1-docker.pkg.dev/deploy-app-to-a-gke-cluster/deploy-app-to-a-gka-cluster/deploy-app-to-a-gka-cluster:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
